export const actions = {
	ADD_TO_BASKET: 'ADD_TO_BASKET',
	REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',

	ADD_TO_BASKET_SUCCESS: 'ADD_TO_BASKET_SUCCESS',
	ADD_TO_BASKET_FAILED: 'ADD_TO_BASKET_FAILED',

	ADD_CATEGORY_SLUG: 'ADD_CATEGORY_SLUG',

	RESTAURANTS: 'RESTAURANTS',
	CATEGORIES: 'CATEGORIES',

	RESTAURANT_SEARCH: 'RESTAURANT_SEARCH',

	BASKET_STATUS: 'BASKET_STATUS',

	EMPTY_BASKET: 'EMPTY_BASKET',

	BASKET_QUANTITY_CHANGE: 'BASKET_QUANTITY_CHANGE',
	DISH_OPTIONS_QUANTITY_CHANGE: 'DISH_OPTIONS_QUANTITY_CHANGE',

	SEND_MESSAGE: 'SEND_MESSAGE',
	SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
	SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',

	FETCH_USER: 'FETCH_USER',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILED: 'FETCH_USER_FAILED',

	CHAT_STATUS: 'CHAT_STATUS',
	CHAT_STATUS_SUCCESS: 'CHAT_STATUS_SUCCESS',
	CHAT_STATUS_FAILED: 'CHAT_STATUS_FAILED',

	FETCH_ROOM: 'FETCH_ROOM',
	FETCH_ROOM_SUCCESS: 'FETCH_ROOM_SUCCESS',
	FETCH_ROOM_FAILED: 'FETCH_ROOM_FAILED',

	AUTHENTICATION: 'AUTHENTICATION',
	AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
	AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
};
